// File generated by FlutterFire CLI.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9upCcQwA_KAcoy7kJnvoI-XrRh6HzVTI',
    appId: '1:242379693775:web:a9fb50032994ce96ed21ba',
    messagingSenderId: '242379693775',
    projectId: 'timeline-4c076',
    authDomain: 'timeline-4c076.firebaseapp.com',
    storageBucket: 'timeline-4c076.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsEKcNRoBHj5dEq-HvWaVgqdgwUI18CK4',
    appId: '1:242379693775:android:212b0efc0040b7e4ed21ba',
    messagingSenderId: '242379693775',
    projectId: 'timeline-4c076',
    storageBucket: 'timeline-4c076.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHvlPAT7dhXTAwCVCoOw0dyGy8Y2DS1ds',
    appId: '1:242379693775:ios:b059d5789e7a58a2ed21ba',
    messagingSenderId: '242379693775',
    projectId: 'timeline-4c076',
    storageBucket: 'timeline-4c076.appspot.com',
    iosBundleId: 'com.timelineapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHvlPAT7dhXTAwCVCoOw0dyGy8Y2DS1ds',
    appId: '1:242379693775:ios:b059d5789e7a58a2ed21ba',
    messagingSenderId: '242379693775',
    projectId: 'timeline-4c076',
    storageBucket: 'timeline-4c076.appspot.com',
    iosBundleId: 'com.timelineapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9upCcQwA_KAcoy7kJnvoI-XrRh6HzVTI',
    appId: '1:242379693775:web:21a5b68a00d026c0ed21ba',
    messagingSenderId: '242379693775',
    projectId: 'timeline-4c076',
    authDomain: 'timeline-4c076.firebaseapp.com',
    storageBucket: 'timeline-4c076.appspot.com',
  );

}